config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get '/good_bye/:id' => 'static_pages#good_bye', as: :good_bye
  post '/' => 'static_pages#create_suggestion'

  get '/get_cities' => 'static_pages#get_cities', as: :get_cities
  get '/privacy_policy' => 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service' => 'static_pages#terms_of_service', as: :terms_of_service

  get '/distributor_request' => 'static_pages#new_distributor_request', as: :distributor_request
  post '/distributor_request' => 'static_pages#create_distributor_request'
  get '/callbacks/bbva/:id' => 'static_pages#bbva_callback', as: :bbva_callback

  get 'log_in/' => 'sessions#new'
  post   'log_in/'   => 'sessions#create'
  delete 'log_out/'  => 'sessions#destroy'
  get 'forgot_password' => 'sessions#forgot_password', as: :forgot_password
  post 'forgot_password' => 'sessions#forgot_password'
  get 'recover_password/:token' => 'sessions#recover_password', as: :recover_password
  post 'recover_password/:token' => 'sessions#recover_password'
  post 'update_password' => 'sessions#update_password', as: :update_password

  get '/products' => 'products#index', as: :products
  get '/products/:id' => 'products#show', as: :product
  post '/products/:id/ask' => 'products#ask', as: :product_ask

  get '/tips&recipes' => "tips#index", as: :tips
  post '/tips&recipes/:id/new_comment' => "tips#create_comment", as: :create_tip_comment
  get '/tips&recipes/:id' => "tips#show", as: :tip

  namespace :admin do
    get '/' => 'welcome#index', as: :welcome
    get '/suggestions' => 'welcome#suggestions', as: :suggestions
    post '/suggestion/:id/send_answer' => 'welcome#answer_suggestion', as: :answer_suggestion
    get '/notifications' => 'welcome#notifications', as: :notifications
    post '/update_ui_theme/:theme' => 'welcome#update_ui_theme', as: :update_ui_theme

    get '/clients' => 'clients#index', as: :clients
    get '/clients/:id' => 'clients#show', as: :client
    get '/clients/:id/orders' => 'clients#orders', as: :client_orders
    get '/clients/:id/prices' => 'clients#prices', as: :client_prices
    get '/clients/:id/revisions' => 'clients#revisions', as: :client_revisions
    get '/clients/:id/visits' => 'clients#visits', as: :client_visits

    get 'mexico-db/states' => 'mexico_db#index', as: :mexico_db
    get 'mexico-db/states/:id' => 'mexico_db#state', as: :mexico_state
    put 'mexico-db/states/:id' => 'mexico_db#update_state_lada'
    put 'mexico-db/states/cities/:id' => 'mexico_db#update_city', as: :mexico_city
    post 'mexico-db/states/cities' => 'mexico_db#create_city', as: :create_city

    resources :banks, except: :show do
      resources :bank_accounts, except: :show, as: 'accounts'
    end

    resources :site_workers do
      get 'permissions/edit', action: :edit_permissions, on: :member, as: :edit_permissions
      put 'permissions', action: :update_permissions, on: :member, as: :update_permissions
    end

    resources :distributors
    resources :distributor_regions, path: 'distributor/:dist_id/regions', except: [ :edit, :update, :show, :new ]
    get '/distributors/candidates/list' => 'distributors#candidates', as: :distributor_candidates
    post '/distributors/candidate/:id/answer' => 'distributors#answer_candidate', as: :answer_candidate

    get 'distributor_work/clients/' => 'distributor_work#index', as: :distributor_work_clients
    put 'distributor_work/clients/:id/take' => 'distributor_work#take_client', as: :distributor_work_take_client
    get 'distributor_work/my_clients/' => 'distributor_work#my_clients', as: :distributor_work_my_clients
    get 'distributor_work/client/:id/prices' => 'distributor_work#prices', as: :distributor_work_client_prices
    post 'distributor_work/client/:id/prices' => 'distributor_work#create_prices', as: :distributor_work_client_create_prices
    get 'distributor_work/my_clients/orders' => 'distributor_work#orders', as: :distributor_work_orders

    get 'distributor_work/client/:id/messages' => 'distributor_work#messages', as: :distributor_work_client_messages
    post 'distributor_work/client/:id/messages' => 'distributor_work#create_message'
    post 'distributor_work/client/:id/transfer' => 'distributor_work#transfer_client', as: :distributor_work_transfer_client

    resources :products
    get '/products/:id/photo/:photo_id/update' => "products#set_principal_photo", as: :products_set_principal
    get '/products/:id/photo/:photo_id/destroy' => "products#destroy_photo", as: :products_photo_destroy
    resources :product_questions, only: [ :index, :create ]
    get 'product_questions/answered' => 'product_questions#answered', as: :product_answered_questions

    resources :warehouses
    resources :warehouse_regions, path: 'warehouses/:warehouse_id/regions', except: [ :edit, :update, :show, :new ]

    resources :warehouse_products, path: 'warehouses/:warehouse_id/products', only: [ :index ]

    get 'warehouses/batch/search' => 'warehouses#batch_search', as: :batch_search
    get 'warehouses/:warehouse_id/inventory/impression_format' => 'warehouses#inventory', as: :inventory

    get 'warehouses/:warehouse_id/products/:id/stock_details' => 'warehouse_products#stock_details', as: :warehouse_products_stock_details
    put 'warehouses/:warehouse_id/products/:id/stock_details' => 'warehouse_products#update_stock'

    get 'chief/warehouses/:warehouse_id/products' => 'warehouse_products#chief_index', as: :chief_warehouse_products
    post 'chief/warehouses/:warehouse_id/products/:id/prepare_for_shipment' => 'warehouse_products#prepare_product_for_shipment', as: :prepare_product_for_shipment
    delete 'chief/warehouses/:warehouse_id/products/preparations/:id' => 'warehouse_products#discard_shipment_preparation', as: :discard_shipment_preparation
    put 'chief/warehouses/:warehouse_id/products/:id/update_min_stock' => 'warehouse_products#update_min_stock', as: :update_product_min_stock

    get 'chief/warehouses/:warehouse_id/shipments' => 'warehouse_products#chief_shipments', as: :chief_shipments
    post 'chief/warehouses/:warehouse_id/shipments' => 'warehouse_products#create_shipment'
    get 'chief/warehouses/:warehouse_id/shipment/:id/details' => 'warehouse_products#chief_shipment_details', as: :chief_shipment_details
    delete 'chief/warehouses/:warehouse_id/shipment/:id' => 'warehouse_products#destroy_shipment', as: :chief_destroy_shipment

    post 'chief/warehouses/print_qr' => 'warehouse_products#print_qr', as: :print_qr

    get 'warehouses/:warehouse_id/shipments' => 'warehouse_products#shipments', as: :shipments
    get 'warehouses/:warehouse_id/shipment/:id/details' => 'warehouse_products#shipment_details', as: :shipment_details
    post 'warehouses/:warehouse_id/shipment/:id/received_it_complete' => 'warehouse_products#receive_complete_shipment', as: :receive_complete_shipment

    post 'warehouses/:warehouse_id/shipment/:id/add_report_quantity_to_stock' => 'warehouse_products#add_report_quantity_to_stock', as: :add_report_quantity_to_stock
    post 'warehouses/:warehouse_id/shipment/:id/difference_report' => 'warehouse_products#create_difference_report', as: :difference_report

    get 'orders/' => 'orders#index', as: :orders
    put 'order/:id/accept_pay/:accept' => 'orders#accept_pay', as: :accept_order_pay

    get 'order/:id/details' => 'orders#details', as: :order_details

    delete 'order/:id' => 'orders#cancel', as: :cancel_order
    put 'order/:id/inspection' => 'orders#inspection', as: :inspection_order
    put 'order/:id/supply_error' => 'orders#supply_error', as: :order_supply_error
    get 'order/:id/capture_details' => 'orders#capture_details', as: :capture_details
    post 'order/:id/capture_details' => 'orders#save_details'
    put 'order/:id/capture_tracking_code' => 'orders#save_tracking_code', as: :capture_tracking_code
    put 'order/:id/delivered' => 'orders#save_as_delivered', as: :order_delivered
    put 'order/:id/invoice' => 'orders#invoice_delivered', as: :order_invoice_delivered
    get 'order/:payment_key/download_payment_file' => 'orders#download_payment_file', as: :download_payment
    put 'order/:id/upload_payment' => 'orders#upload_payment', as: :order_upload_payment

    get 'orders/search' => 'orders#search', as: :orders_search
    get 'order/:id/show_activities' => 'orders#show_activities', as: :show_order_activities

    get 'orders/invoice/download' => 'orders#download_invoice_data', as: :download_orders_invoice_data

    put 'orders/:id/invoice_folio' => 'orders#save_invoice_folio', as: :order_save_invoice_folio

    get 'bank_report/' => 'bank_reports#index', as: :bank_report
    post 'bank_report/' => 'bank_reports#show'

    get "clients/:id/supervisor_visits/" => 'clients#supervisor_visits', as: :supervisor_visits
    get "clients/:id/supervisor_visits/:visit_id/details" => 'clients#supervisor_visit_details', as: :supervisor_visit_details
    get "clients/:id/supervisor_visits/new" => 'clients#new_supervisor_visit', as: :new_supervisor_visit
    post "clients/:id/supervisor_visits/new" => 'clients#create_supervisor_visit'

    get 'statistics' => 'statistics#index', as: :statistics
    post 'statistics/sales' => 'statistics#sales', as: :sales_statistics
    post 'statistics/best_distributors' => 'statistics#best_distributors', as: :best_dist_statistics
    post 'statistics/best_clients' => 'statistics#best_clients', as: :best_clients_statistics

    get 'web' => 'web#index', as: :web
    get 'web/video' => 'web#videos', as: :web_videos
    post 'web/video' => 'web#upload_video'
    delete 'web/video' => 'web#reset_videos'

    get 'web/gallery' => 'web#photos', as: :web_photos
    post 'web/gallery' => 'web#upload_photos'
    delete 'web/gallery/:id' => 'web#destroy_photo', as: :web_destroy_photo

    get 'web/offers' => 'web#offers', as: :web_offers
    post 'web/offers' => 'web#upload_offers'
    delete 'web/offers/:id' => 'web#destroy_offer', as: :web_destroy_offer

app/models/warehouse_product.rb
class WarehouseProduct < ApplicationRecord
  attr_accessor :required_bulk
  attr_accessor :required_quantity
  include HashId
  include Searchable
  
  belongs_to :Warehouse, foreign_key: :warehouse_id
  belongs_to :Product, foreign_key: :product_id

  validates :warehouse_id, :product_id, :existence, presence: true,
    numericality: { only_integer: true }, on: :create

  scope :visible, -> { where(products: {show: true}) }
  scope :active, -> { where(products: {deleted_at: nil})}
  scope :describes_total_stock, -> { where(describes_total_stock: true)}

  def self.by_category(category)
    return all unless category.present? and ["hot","cold","frappe"].include? category
    where("products.#{category}" => true)
  end

  def enoughStock?
    return true if self.existence >= self.required_quantity
    return false
  end

  def withdraw(quantity)
    self.required_quantity = quantity
    raise ActiveRecord::RangeError, "Sin stock suficiente" unless self.enoughStock?
    update_attributes(existence: self.existence - required_quantity)
  end

  def supply(to_be_added)
    update_attributes(existence: self.existence + to_be_added)
  end

  def self.return(product_id, quantity)
    unless quantity.kind_of? Integer and quantity > 0
      raise ActiveRecord::RangeError, "Quantity should be a positive integer"
    end
    query = "UPDATE warehouse_products 
      SET existence=(existence+#{quantity}) WHERE
      id=#{product_id}"
    ActiveRecord::Base.connection.execute(query)
  end

  def self.return_for_warehouse(warehouse_id, product_id, batch, quantity)
    unless quantity.kind_of? Integer and quantity > 0
      raise ActiveRecord::RangeError, "Quantity should be a positive integer"
    end

    query = "UPDATE warehouse_products 
      SET existence=(existence+#{quantity}) WHERE
      warehouse_id=#{warehouse_id} and product_id=#{product_id}
      and batch='#{batch}';"
    ActiveRecord::Base.connection.execute(query)
  end
end

app/controllers/api/workers_api/warehouse_products_controller.rb
class Api::WorkersApi::WarehouseProductsController < ApiController
  before_action do
    authenticate_user!(SiteWorker)
  end

  def index
    warehouse_products = @current_user.Warehouse.Products.joins(:Product)
      .where(describes_total_stock: true, products: {deleted_at: nil})
      .order("products.name asc").paginate(page: params[:page], per_page: 20).includes(:Product)
    data = Array.new
    warehouse_products.each do |w_p|
      data << {hash_id: w_p.Product.hash_id, name: w_p.Product.name, existence: w_p.existence, min_stock: w_p.min_stock}
    end

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end

  def existence
    render status: 200, json: {success: false, info: "BATCH_MUST_BE_PRESENT"} and return unless params[:batch]

    wp = @current_user.Warehouse.Products.where(batch: params[:batch]).take
    render status: 200, json: {success: false, info: "WAREHOUSE_PRODUCT_NOT_FOUND"} and return unless wp

    data = { product_id: wp.product_id, batch: wp.batch, existence: wp.existence }

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end

  def create_inventory_report
    render status: 200, json: {success: false, info: "REPORT_DETAILS_REQUIRED"} and return unless params[:report]

    inventory_report = InventoryReport.new(inventory_report_params)
    inventory_report.worker_id = @current_user.id
    inventory_report.warehouse_id = @current_user.warehouse_id

    worker = SiteWorker.joins(:Permissions)
      .where(warehouse_id: @current_user.warehouse_id)
      .where(permissions: {category: "WAREHOUSE_MANAGER"}).take

    render status: 200, json: {success: false, info: "NO_ONE_TO_REPORT_AT"} and return unless worker

    if inventory_report.save
      Notification.create(worker_id: worker.id, icon: "fa fa-file-text-o", description: "Nuevo reporte de inventario", 
        url: "/admin/warehouse/#{@current_user.Warehouse.hash_id}/inventory_report/#{inventory_report.id}")

      render status: 200, json: {success: true, info: "SAVED"}
    else
      render status: 200, json: {success: false, info: "NOT_SAVED"}
    end
  end

  private
    def inventory_report_params
      params.require(:report).permit(:product_id, :batch, :description, :comment)
    end
end

app/views/admin/warehouse_products/_min_existence_form.html.erb
<%= form_for(:warehouse_product,
    url: admin_update_product_min_stock_path(@warehouse.hash_id, "0x0"),
    remote: true, method: :put, html: {id: "min-stock-form"}) do |f| %>

    <table class="full-width">
      <tr>
          <td><%= f.label :min_stock, "Nuevo stock mínimo" %></td>
          <td class="table-padd"><%= f.number_field :min_stock, placeholder: "0", min: 0, max: 99999, class: "form-control" %></td>
          <td><%= f.submit "Modificar", data: { confirm: "Seguro(a) de modificar el stock mínimo?" },
      class: "btn btn-primary" %></td>
      </tr>
    </table>

<% end %>

app/views/admin/warehouse_products/_presentation_table.html.erb
<div class="col-lg-12">
  <div class="ibox">
  	<div class="ibox-content">

  			<div class="row m-b-sm m-t-sm">
          <div class="col-md-7">
            <input type="text" class="form-control input-sm m-b-xs" id="filter" maxlength="25" placeholder="Buscar en tabla">
          </div>
          <div class="col-md-3">
            <% if @current_user.has_permission?("warehouse_manager@receive_shipments") %>
    					<%= link_to(admin_shipments_path(@warehouse.hash_id), class: "btn btn-white btn-sm full-width") do %>
    						<i class="fa fa-truck"></i> Envíos a mi almacén
    					<% end %>
            <% end %>

            <% if @current_user.has_permission_category?("warehouse_manager") %>
              <%= link_to(admin_inventory_reports_path(@warehouse.hash_id), class: "btn btn-white btn-sm full-width") do %>
                <i class="fa fa-file-text-o"></i> Reportes de Inventario
              <% end %>
            <% end %>
  				</div>
  			</div>

  			<table class="footable table table-stripped  toggle-arrow-tiny" data-page-size="15" data-filter=#filter>
  					<thead>
    					<tr>
                  <th data-sort-ignore="true"></th>
    					    <!--<th data-hide="phone" data-sort-ignore="true"></th>-->
                  <th>Clave</th>
    					    <th>Nombre</th>
    					    <th data-hide="phone" data-type="numeric">Existencia</th>
    					    <th data-hide="phone" data-type="numeric">Stock Mínimo</th>
    					</tr>
  					</thead>
  					<tbody>
            <% @products.each do |wp| %>
              <% p = wp.Product %>
  					  <tr class="<%= wp.existence < wp.min_stock ? 'bg-warning' : '' %>">
                <td></td>
                <td><%= p.hash_id %></td>
    						<td><%= p.name %></td>
    						<td>
                  <button type="button" class="btn btn-primary btn-sm m-r-sm"
                          onclick="update_shipment_preparations_form('<%=p.name%>', '<%=p.id%>', <%=wp.id%>, <%=wp.existence%>);">
                          <%= wp.existence %>
                  </button>
                  <%= link_to "Detalles",
                  admin_warehouse_products_stock_details_path(params[:warehouse_id], p.id),
                  class: "btn btn-white btn-sm" %>
                </td>
    						<td>
                  <button type="button" class="btn btn-warning btn-sm m-r-sm">
                          <%= wp.min_stock %>
                  </button>
                </td>
  					  </tr>
  					<% end %>
  					</tbody>
            <tfoot>
              <tr>
                <td colspan="7">
                  <div class="pull-right">
                    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
                  </div>
                </td>
              </tr>
            </tfoot>
  			</table>

        <script>
            $(document).ready(function() {
                $(".footable").footable();
            });
        </script>

  	</div>
  </div>
</div>

app/views/admin/warehouse_products/_product_preparated.html.erb
<div id="<%=product_key%>" class="col-lg-3 col-md-4">
  <div class="hr-line-solid-light"></div>
  <p><b>Cantidad:</b> <%=product["quantity"]%></p>
  <p><b>Lote:</b> <%=product["batch"]%></p>
  <p><b>Caducidad:</b> <%=product["expiration_date"]%></p>
  <%= link_to admin_discard_shipment_preparation_path(params[:warehouse_id], product_key), 
    method: :delete, class: "btn btn-danger btn-sm", remote: true,
    data: {confirm: "Seguro(a) de eliminar este lote de los preparativos"} do %>
    <i class="fa fa-trash"></i> Borrar
  <% end %>
</div>

app/views/admin/warehouse_products/_shipment.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="2"><h4>Datos del Envío:</h4></th>
      </tr>
    </thead>
    <tr>
      <td><b>Revisado:</b></td>
      <td>
        <% if s.reviewed %>
          <span class="badge badge-primary">
            <i class="fa fa-check"></i>&nbsp; Revisado
          </span>
        <% else %>
          <span class="badge badge-danger">
            <i class="fa fa-times"></i>&nbsp; Sin revisar
          </span>
        <% end %>
      </td>
    </tr>
    <tr>
      <td><b>Fecha del envío:</b></td>
      <td><%= l(s.created_at, format: :long) %></td>
    </tr>
    <tr>
      <td><b>Jefe de almacén que autorizó el envío:</b></td>
      <td><%= link_to s.Chief.name, admin_site_worker_path(s.Chief.hash_id) %></td>
    </tr>
    <% if !s.origin_warehouse_id.nil? %>
      <tr><td><b>almacén que traspasó: </b></td>
        <td><%= s.OriginWarehouse.name %></td></tr>
    <% end %>
    <tr>
      <td><b>Estatus:</b></td>
      <td>
        <% if s.got_safe_to_destination %>
          <l class="text-info">Llegó completo</l>
        <% elsif s.got_safe_to_destination == false %>
          <l class="text-danger">No llegó completo</l>
        <% else %>
          <l class="text-warning">Está en camino</l>
        <% end %>
      </td>
    </tr>
    <% if s.got_safe_to_destination or s.got_safe_to_destination == false %>
      <tr>
        <td><b>Trabajador que recibió el envío:</b></td>
        <td><%= link_to s.Worker.name, admin_site_worker_path(s.Worker.hash_id) %></td>
      </tr>
    <% end %>
  </table>

app/views/admin/warehouse_products/_shipments.html.erb
<% provide(:title, "Envíos de almacén") %>
<%= render partial: "/shared/admin/header_band", locals: {title: "Envíos de almacén", 
  labels: ["Almacenes", @warehouse.name, "Envíos de almacén"], 
  links: [admin_warehouses_path, admin_warehouse_products_path(@warehouse.hash_id)]} %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <%= render "/shared/warehouse_head_bar" %>

    <div class="row">
      <div class="col-lg-12">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Lista de envío(s) al almacén</h5>
            <div class="ibox-tools">
              <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
              </a>
            </div>
          </div>
          <div class="ibox-content">
            <% @shipments.each do |s| %>
              <div class="row">
                <div class="col-sm-10 b-r margin-bot-resp">
                  <%= render partial: "shipment", locals: {s: s} %>
                </div>
                <div class="hr-line-dashed pro-mobile"></div>
                <div class="col-sm-2 b-r text-center">
                  <h4>Revisar envío<br>
                  <%= link_to details_url.sub("s_id", s.id.to_s) do %>
                    <i class="fa fa-eye size-icon"></i>
                  <% end %>
                  <br>
                  <% if @current_user.has_permission?("warehouse_products@delete_shipments") and !s.reviewed %>
                    <h4>Eliminar<br>
                    <%= link_to admin_chief_destroy_shipment_path(params[:warehouse_id], s.id),
                      method: :delete, data: {confirm: "Estas seguro(a) de eliminar el envío?"} do %>
                      <i class="fa fa-trash size-icon"></i>
                    <% end %>
                  <% end %>
                  <br>
                </div>
              </div>
              <div class="hr-line-dashed"></div>
            <% end %>
            <%= will_paginate @shipments, renderer: BootstrapPagination::Rails %>
          </div>
        </div>
      </div>
    </div>
    <br>

  </div>
</div>

app/views/admin/warehouse_products/_transfer_preparation_form.html.erb
<%= form_for(:warehouse_product,
    url: admin_prepare_product_for_shipment_path(@warehouse.hash_id, "0x0"),
    remote: true, method: :post, html: {id: "transfer_preparation_form"}) do |f| %>

    <%= f.label :quantity, "Cantidad a transferir" %>
    <%= f.number_field :quantity, { class: "form-control m-b", placeholder: "0",
                                    min: 0, max: 999999, step: 0, required: true} %>

    <%= f.label :batch, "Número de lote" %>
    <%= f.text_field :batch, class: "form-control m-b", maxlenght: 20, required: true %>

    <%= f.hidden_field :name %>

    <%= f.submit "Agregar producto a los preparativos de transferencia", class: "btn btn-primary btn-sm" %>

<% end %>

app/views/admin/warehouse_products/chief_shipments.html.erb
<% chief_shipment_details_url = admin_chief_shipment_details_path(@warehouse.hash_id, "s_id") %>
<%= render partial: "shipments", locals: {details_url: chief_shipment_details_url } %>

app/views/admin/warehouse_products/discard_shipment_preparation.js.erb
<% if @remove_container %>
  $("#<%=@k%>").remove();
<% else %>
  $("#<%=params[:id]%>").remove();
<% end %>
$("#dismissible_alerts").append(`<%= j render partial: "/shared/dismissible_alert", 
  locals: {message_type: :success, message: "Eliminado de los preparativos"} %>`);

app/views/admin/warehouse_products/index.html.erb
<% provide(:title, "Almacenes") %>
<%= render partial: "/shared/admin/header_band", locals: {title: "Productos en el almacén", 
  labels: ["Almacenes", "Productos en el almacén"], links: [admin_warehouses_path]} %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <%= render "/shared/warehouse_head_bar" %>

    <div class="row">
      <%= render partial: "presentation_table" %>
    </div>

    <% if @current_user.has_permission?("warehouse_manager@transfer_mercancy") %>
      <div class="row">
        <div class="col-lg-12">
          <div class="ibox ibox-content">
            <h3 class="m-t-none m-b">Preparativos para transferencia</h3>
            <div id="prepare_product_for_shipment">
              <% if session[:shipment_products].present? %>
                <% hash = session[:shipment_products].clone %>
                <% hash.delete("warehouse") %>
                <% hash.keys.each do |k| %>
                  <% products = hash[k] %>
                  <div class="col-md-12 well" id="<%=k%>">
                    <h4 class="m-l">Lote(s) de producto: <small><%= hash[k]["name"] %></small></h4>
                    <% products.keys.each do |p_k| %>
                      <% if p_k != "name" %>
                        <%= render partial: "product_preparated", locals: {product: products[p_k], product_key: p_k} %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>

            <%= form_for(:shipment, url: admin_chief_shipments_path(params[:warehouse_id])) do |f| %>
              <%= f.hidden_field :shipment_type, value: "TRANSFER" %>
              <%= f.hidden_field :chief_id, value: @current_user.id %>
              <%= f.hidden_field :origin_warehouse_id, value: @warehouse.id %>

              <%= select_tag "shipment[target_warehouse_id]", options_from_collection_for_select(
              @warehouses, "id", "name"), prompt: "Selecciona...", class: "form-control m-b", required: true %>

              <%= f.submit "Enviar productos al almacén!", class: "btn btn-primary",
              data: {confirm: "Seguro(a) de registrar el envío de productos?" }%>
            <% end %>
          </div>
        </div>
      <% end # if @actions["TRANSFER_MERCANCY"] # %>
    </div>
  </div>
</div>

<%= render "shared/modal" %>

<% if @current_user.has_permission?("warehouse_manager@transfer_mercancy") %>
<script type="text/javascript">
  function update_shipment_preparations_form(product_name, product_id, warehouse_product_id, existencia) {
    modal = $("#modal")
    modal.find(".modal-title").html("Transferir existencia de: "+product_name);
    modal.find(".modal-body").html("<%= j render 'transfer_preparation_form' %>");

    $("#warehouse_product_name").val(product_name);
    $("#warehouse_product_quantity").attr("max", existencia);

    var _href = $("#transfer_preparation_form").attr("action");
    $("#transfer_preparation_form").get(0).setAttribute("action", _href.replace("0x0", product_id));

    modal.modal("show");
  }
</script>
<% end # if @actions["TRANSFER_MERCANCY"] # %>

app/views/admin/warehouse_products/shipments.html.erb
<% shipment_details_url = admin_shipment_details_path(@warehouse.hash_id, "s_id") %>
<%= render partial: "shipments", locals: {details_url: shipment_details_url } %>

app/views/admin/warehouse_products/update_min_stock.js.erb
<% if params[:warehouse_product][:min_stock].to_i > 0 %>
  $("#min-stock-<%= params[:id] %>").html(<%=params[:warehouse_product][:min_stock].to_i%>);
  $("#modal").modal("hide");
<% else %>
  $("#dismissible_alerts").append(`<%= j render partial: "/shared/dismissible_alert", 
    locals: {message_type: :info, message: "La cantidad debe ser mayor que cero"} %>`);
<% end %>