config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get '/good_bye/:id' => 'static_pages#good_bye', as: :good_bye
  post '/' => 'static_pages#create_suggestion'

  get '/get_cities' => 'static_pages#get_cities', as: :get_cities
  get '/privacy_policy' => 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service' => 'static_pages#terms_of_service', as: :terms_of_service

  get '/distributor_request' => 'static_pages#new_distributor_request', as: :distributor_request
  post '/distributor_request' => 'static_pages#create_distributor_request'
  get '/callbacks/bbva/:id' => 'static_pages#bbva_callback', as: :bbva_callback

  get 'log_in/' => 'sessions#new'
  post   'log_in/'   => 'sessions#create'
  delete 'log_out/'  => 'sessions#destroy'
  get 'forgot_password' => 'sessions#forgot_password', as: :forgot_password
  post 'forgot_password' => 'sessions#forgot_password'
  get 'recover_password/:token' => 'sessions#recover_password', as: :recover_password
  post 'recover_password/:token' => 'sessions#recover_password'
  post 'update_password' => 'sessions#update_password', as: :update_password

  get '/products' => 'products#index', as: :products
  get '/products/:id' => 'products#show', as: :product
  post '/products/:id/ask' => 'products#ask', as: :product_ask

  get '/tips&recipes' => "tips#index", as: :tips
  post '/tips&recipes/:id/new_comment' => "tips#create_comment", as: :create_tip_comment
  get '/tips&recipes/:id' => "tips#show", as: :tip

  namespace :admin do
    get '/' => 'welcome#index', as: :welcome
    get '/suggestions' => 'welcome#suggestions', as: :suggestions
    post '/suggestion/:id/send_answer' => 'welcome#answer_suggestion', as: :answer_suggestion
    get '/notifications' => 'welcome#notifications', as: :notifications
    post '/update_ui_theme/:theme' => 'welcome#update_ui_theme', as: :update_ui_theme

    get '/clients' => 'clients#index', as: :clients
    get '/clients/:id' => 'clients#show', as: :client
    get '/clients/:id/orders' => 'clients#orders', as: :client_orders
    get '/clients/:id/prices' => 'clients#prices', as: :client_prices
    get '/clients/:id/revisions' => 'clients#revisions', as: :client_revisions
    get '/clients/:id/visits' => 'clients#visits', as: :client_visits

    get 'mexico-db/states' => 'mexico_db#index', as: :mexico_db
    get 'mexico-db/states/:id' => 'mexico_db#state', as: :mexico_state
    put 'mexico-db/states/:id' => 'mexico_db#update_state_lada'
    put 'mexico-db/states/cities/:id' => 'mexico_db#update_city', as: :mexico_city
    post 'mexico-db/states/cities' => 'mexico_db#create_city', as: :create_city

    resources :banks, except: :show do
      resources :bank_accounts, except: :show, as: 'accounts'
    end

    resources :site_workers do
      get 'permissions/edit', action: :edit_permissions, on: :member, as: :edit_permissions
      put 'permissions', action: :update_permissions, on: :member, as: :update_permissions
    end

    resources :distributors
    resources :distributor_regions, path: 'distributor/:dist_id/regions', except: [ :edit, :update, :show, :new ]
    get '/distributors/candidates/list' => 'distributors#candidates', as: :distributor_candidates
    post '/distributors/candidate/:id/answer' => 'distributors#answer_candidate', as: :answer_candidate

    get 'distributor_work/clients/' => 'distributor_work#index', as: :distributor_work_clients
    put 'distributor_work/clients/:id/take' => 'distributor_work#take_client', as: :distributor_work_take_client
    get 'distributor_work/my_clients/' => 'distributor_work#my_clients', as: :distributor_work_my_clients
    get 'distributor_work/client/:id/prices' => 'distributor_work#prices', as: :distributor_work_client_prices
    post 'distributor_work/client/:id/prices' => 'distributor_work#create_prices', as: :distributor_work_client_create_prices
    get 'distributor_work/my_clients/orders' => 'distributor_work#orders', as: :distributor_work_orders

    get 'distributor_work/client/:id/messages' => 'distributor_work#messages', as: :distributor_work_client_messages
    post 'distributor_work/client/:id/messages' => 'distributor_work#create_message'
    post 'distributor_work/client/:id/transfer' => 'distributor_work#transfer_client', as: :distributor_work_transfer_client

    resources :products
    get '/products/:id/photo/:photo_id/update' => "products#set_principal_photo", as: :products_set_principal
    get '/products/:id/photo/:photo_id/destroy' => "products#destroy_photo", as: :products_photo_destroy
    resources :product_questions, only: [ :index, :create ]
    get 'product_questions/answered' => 'product_questions#answered', as: :product_answered_questions

    resources :warehouses
    resources :warehouse_regions, path: 'warehouses/:warehouse_id/regions', except: [ :edit, :update, :show, :new ]

    resources :warehouse_products, path: 'warehouses/:warehouse_id/products', only: [ :index ]

    get 'warehouses/batch/search' => 'warehouses#batch_search', as: :batch_search
    get 'warehouses/:warehouse_id/inventory/impression_format' => 'warehouses#inventory', as: :inventory

    get 'warehouses/:warehouse_id/products/:id/stock_details' => 'warehouse_products#stock_details', as: :warehouse_products_stock_details
    put 'warehouses/:warehouse_id/products/:id/stock_details' => 'warehouse_products#update_stock'

    get 'chief/warehouses/:warehouse_id/products' => 'warehouse_products#chief_index', as: :chief_warehouse_products
    post 'chief/warehouses/:warehouse_id/products/:id/prepare_for_shipment' => 'warehouse_products#prepare_product_for_shipment', as: :prepare_product_for_shipment
    delete 'chief/warehouses/:warehouse_id/products/preparations/:id' => 'warehouse_products#discard_shipment_preparation', as: :discard_shipment_preparation
    put 'chief/warehouses/:warehouse_id/products/:id/update_min_stock' => 'warehouse_products#update_min_stock', as: :update_product_min_stock

    get 'chief/warehouses/:warehouse_id/shipments' => 'warehouse_products#chief_shipments', as: :chief_shipments
    post 'chief/warehouses/:warehouse_id/shipments' => 'warehouse_products#create_shipment'
    get 'chief/warehouses/:warehouse_id/shipment/:id/details' => 'warehouse_products#chief_shipment_details', as: :chief_shipment_details
    delete 'chief/warehouses/:warehouse_id/shipment/:id' => 'warehouse_products#destroy_shipment', as: :chief_destroy_shipment

    post 'chief/warehouses/print_qr' => 'warehouse_products#print_qr', as: :print_qr

    get 'warehouses/:warehouse_id/shipments' => 'warehouse_products#shipments', as: :shipments
    get 'warehouses/:warehouse_id/shipment/:id/details' => 'warehouse_products#shipment_details', as: :shipment_details
    post 'warehouses/:warehouse_id/shipment/:id/received_it_complete' => 'warehouse_products#receive_complete_shipment', as: :receive_complete_shipment

    post 'warehouses/:warehouse_id/shipment/:id/add_report_quantity_to_stock' => 'warehouse_products#add_report_quantity_to_stock', as: :add_report_quantity_to_stock
    post 'warehouses/:warehouse_id/shipment/:id/difference_report' => 'warehouse_products#create_difference_report', as: :difference_report

    get 'orders/' => 'orders#index', as: :orders
    put 'order/:id/accept_pay/:accept' => 'orders#accept_pay', as: :accept_order_pay

    get 'order/:id/details' => 'orders#details', as: :order_details

    delete 'order/:id' => 'orders#cancel', as: :cancel_order
    put 'order/:id/inspection' => 'orders#inspection', as: :inspection_order
    put 'order/:id/supply_error' => 'orders#supply_error', as: :order_supply_error
    get 'order/:id/capture_details' => 'orders#capture_details', as: :capture_details
    post 'order/:id/capture_details' => 'orders#save_details'
    put 'order/:id/capture_tracking_code' => 'orders#save_tracking_code', as: :capture_tracking_code
    put 'order/:id/delivered' => 'orders#save_as_delivered', as: :order_delivered
    put 'order/:id/invoice' => 'orders#invoice_delivered', as: :order_invoice_delivered
    get 'order/:payment_key/download_payment_file' => 'orders#download_payment_file', as: :download_payment
    put 'order/:id/upload_payment' => 'orders#upload_payment', as: :order_upload_payment

    get 'orders/search' => 'orders#search', as: :orders_search
    get 'order/:id/show_activities' => 'orders#show_activities', as: :show_order_activities

    get 'orders/invoice/download' => 'orders#download_invoice_data', as: :download_orders_invoice_data

    put 'orders/:id/invoice_folio' => 'orders#save_invoice_folio', as: :order_save_invoice_folio

    get 'bank_report/' => 'bank_reports#index', as: :bank_report
    post 'bank_report/' => 'bank_reports#show'

    get "clients/:id/supervisor_visits/" => 'clients#supervisor_visits', as: :supervisor_visits
    get "clients/:id/supervisor_visits/:visit_id/details" => 'clients#supervisor_visit_details', as: :supervisor_visit_details
    get "clients/:id/supervisor_visits/new" => 'clients#new_supervisor_visit', as: :new_supervisor_visit
    post "clients/:id/supervisor_visits/new" => 'clients#create_supervisor_visit'

    get 'statistics' => 'statistics#index', as: :statistics
    post 'statistics/sales' => 'statistics#sales', as: :sales_statistics
    post 'statistics/best_distributors' => 'statistics#best_distributors', as: :best_dist_statistics
    post 'statistics/best_clients' => 'statistics#best_clients', as: :best_clients_statistics

    get 'web' => 'web#index', as: :web
    get 'web/video' => 'web#videos', as: :web_videos
    post 'web/video' => 'web#upload_video'
    delete 'web/video' => 'web#reset_videos'

    get 'web/gallery' => 'web#photos', as: :web_photos
    post 'web/gallery' => 'web#upload_photos'
    delete 'web/gallery/:id' => 'web#destroy_photo', as: :web_destroy_photo

    get 'web/offers' => 'web#offers', as: :web_offers
    post 'web/offers' => 'web#upload_offers'
    delete 'web/offers/:id' => 'web#destroy_offer', as: :web_destroy_offer

app/models/order_action.rb
class OrderAction < ApplicationRecord
  belongs_to :Worker, class_name: :SiteWorker, foreign_key: :worker_id
  belongs_to :Order, foreign_key: :order_id
end

app/controllers/api/distributor_api/orders_controller.rb
class Api::DistributorApi::OrdersController < ApiController
  before_action do
    authenticate_user!(Distributor)
  end

  def index
    if params[:client].blank?
      orders = @current_user.Orders.order(updated_at: :desc).limit(100)
        .paginate(page: params[:page], per_page: 25).includes(:Client, City: :State)
    else
      client = Client.find_by!(hash_id: params[:client])
      if !client.blank?
        orders = Order.where(client_id: client.id).order(updated_at: :desc).limit(100)
          .paginate(page: params[:page], per_page: 25).includes(City: :State)
        @current_user.updateRevision(client)
      else
        render status: 200, json: {success: false, info: "CLIENT_NOT_FOUND"} and return
      end
    end

    data = Array.new
    orders.each do |order|
      data << {hash_id: order.hash_id, client_username: order.Client.username, client_hash_id: order.Client.hash_id,
        date: I18n.l(order.created_at, format: :long), total: order.total, status: I18n.t(order.state), city: order.City.name, state: order.City.State.name }
    end
    home_img = @current_user.home_img.url
    avatar = @current_user.avatar_url

    render status: 200, json: {success: true, info: "DATA_RETURNED", 
      avatar: avatar, home_img: home_img, data: data}
  end

  def show
    order = Order.find_by!(hash_id: params[:id])

    fiscal_data = order.Client.FiscalData
    warehouse = order.Warehouse
    details = order.Details

    data = Hash.new
    data[:shipping_cost] = order.shipping_cost
    data[:cancel_description] = order.cancel_description
    data[:reject_description] = order.reject_description

    city = warehouse.City
    warehouse_data = {address: warehouse.address, city: city.name,
      state: city.State.name, lada: city.lada, telephone: warehouse.telephone }

    data[:warehouse_data] = warehouse_data
    data[:fiscal_data] = fiscal_data
    data[:state_name] = fiscal_data.City.State.name if fiscal_data
    data[:city_name] = fiscal_data.City.name if fiscal_data

    details_data = Array.new
    details.each do |detail|
      product = detail.Product
      details_data << {product: product.name, presentation: product.presentation,
        product_unit_price: detail.price, quantity: detail.quantity, iva: detail.iva, ieps: detail.ieps,
        total_iva: detail.total_iva, total_ieps: detail.total_ieps}
    end
    data[:order_details] = details_data

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end
end

app/controllers/api/workers_api/orders_controller.rb
class Api::WorkersApi::OrdersController < ApiController
  before_action do
    authenticate_user!(SiteWorker)
  end

  def count
    orders_count = Order.where(state: "PAYMENT_ACCEPTED", warehouse_id: @current_user.warehouse_id).size

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: orders_count}
  end

  def index
    state = params[:state].present? ? params[:state] : ["PAYMENT_ACCEPTED","LOCAL"]

    orders = Order.where(state: state, warehouse_id: @current_user.warehouse_id)
      .order(created_at: :asc).paginate(page: params[:page], per_page: 25).includes(:Client, :Distributor)

    data = Array.new
    orders.each do |order|
      client = order.Client
      distributor = order.Distributor
      hash = {folio: order.hash_id, date: order.created_at, client: order.client_id,
        client_avatar: client.avatar_url, client_username: client.name, state: order.state,
        distributor: order.distributor_id, distributor_avatar: nil, distributor_username: nil}

      if distributor
        hash[:distributor_avatar] = distributor.avatar_url
        hash[:distributor_username] = distributor.username
      end
      data << hash
    end

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end

  def show
    order = Order.find_by!(hash_id: params[:id])

    warehouse = order.Warehouse
    details = order.Details.includes(:Product)

    data = Hash.new
    data[:shipping_cost] = order.shipping_cost

    city = warehouse.City
    warehouse_data = {address: warehouse.address, city: city.name,
      state: city.State.name, lada: city.lada, telephone: warehouse.telephone }

    data[:warehouse_data] = warehouse_data

    details_data = Array.new
    details.each do |detail|
      product = detail.Product
      details_data << {id: product.id, product: product.name, presentation: product.presentation,
        product_unit_price: detail.price, quantity: detail.quantity, iva: detail.iva, ieps: detail.ieps,
        total_iva: detail.total_iva, total_ieps: detail.total_ieps}
    end
    data[:order_details] = details_data

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end

  def supplied
    orders = Order.where(state: "BATCHES_CAPTURED", warehouse_id: @current_user.warehouse_id).order(created_at: :asc).paginate(page: params[:page], per_page: 25)
    data = Array.new
    orders.each do |order|
      data << {folio: order.hash_id, date: order.created_at, client: order.client_id, distributor: order.distributor_id}
    end

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end

  def save_details
    order = Order.find_by!(hash_id: params[:id])
    unless ["PAYMENT_ACCEPTED", "LOCAL"].include? order.state 
      render status: 200, json: {success: false, info: "ORDER_NOT_ELIGIBLE"} and return
    end

    ActiveRecord::Base.transaction do
      order_details = OrderDetail.required_products_hash(order.id)

      params[:product_id].each_with_index do |product_id, indx|
        detail = OrderProductShipmentDetail.create!(order_id: order.id, batch: params[:batch][indx],
          product_id: product_id, quantity: params[:quantity][indx], warehouse_id: order.warehouse_id)
        detail.warehouse_detail.withdraw(detail.quantity)
        order_details[product_id][:quantity_captured] += detail.quantity
      end
      verify_details_captured(order_details)

      order.state = order.state == "LOCAL" ? "PICKED_UP" : "BATCHES_CAPTURED"
      order.save!
      OrderAction.create!(order_id: order.id, worker_id: @current_user.id, description: "Capturó lotes y cantidades")
    end # Transaction #

    render status: 200, json: {success: true, info: "BATCHES_CAPTURED"}
  rescue ActiveRecord::RecordInvalid => e
    render status: 200, json: {success: false, info: "NOT_SAVED", error: e.record.errors.full_messages[0]}
  rescue ActiveRecord::RangeError
    error = "Las cantidades solicitadas por el cliente y las capturadas no coinciden"
    render status: 200, json: {success: false, info: "NOT_SAVED", error: error}
  end # def save_details #

  private
    def verify_details_captured(details)
      details.keys.each do |product_id|
        if details[product_id][:products_required_by_the_user] != details[product_id][:quantity_captured]
          raise ActiveRecord::RangeError, "Cantidades solicitadas y capturadas no coinciden"
        end
      end
    end
end

app/views/admin/orders/_cancel_order_form.html.erb
<%= form_for :order, url: admin_cancel_order_path(0), method: :delete, html: {id: "cancel_form"} do |f| %>
  <%= f.label :cancel_description, "Descripción del por qué se cancela esta orden/pedido" %>
  <%= f.text_area :cancel_description, class: "form-control m-b", placeholder: "Escribe la razón de la cancelación...", required: true %>
  <%= f.submit "Cancelar la orden", class: "btn btn-danger btn-sm", data:{confirm: "¿Seguro(a) de cancelar la orden?"} %>
<% end %>

app/views/admin/orders/_local_orders_presentation_table.html.erb
<div class="col-lg-12">
  <div class="ibox">
    <div class="ibox-content">

      <%= render "navigation_labels" %>

      <%= form_for :class, url: admin_orders_path, 
        method: :get, id: "search-form" do |f| %>
        <%= hidden_field_tag :type, params[:type] %>
        <div class="input-group">
          <%= f.text_field :search, value: search_params, class: 'form-control',
            placeholder: 'Buscar', maxlength: 20, required: true %>

          <% if params[:distributor].present? %>
            <%= hidden_field_tag :distributor, params[:distributor] %>
          <% end %>

          <span class="input-group-btn">
            <%= f.submit 'Buscar', class: 'btn btn btn-success' %>
          </span>
        </div>
      <% end %>

      <% if @current_user.has_permission?('commissions@create') and params[:distributor].present? %>
        <%= form_tag(admin_commissions_path(distributor: params[:distributor]), id: 'create-commission-form') do %>
          <button class="btn btn-success pull-right" style="margin-top: 2em"
            onclick="$('#create-commission-form')[0].submit();">
            Crear comisión
          </button>
        <% end %>
      <% end %>

      <table class="footable table table-stripped toggle-arrow-tiny" data-filter=#filter>
        <thead>
          <tr>
            <th>Referencia</th>
            <th data-hide="all">Correo electrónico</th>
            <th data-hide="all">Ubicación</th>
            <th data-hide="phone">Cliente</th>
            <th data-hide="all">Teléfono</th>
            <th data-hide="phone,tablet">Distribuidor</th>
            <th>Status</th>
            <th data-type="numeric">Total a pagar</th>
            <th data-hide="all"></th>
            <th>Comprobante</th>
            <th data-hide="all">Fecha de creación</th>
            <th>Acción</th>
            <th data-hide="all"></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |o| %>
            <tr id="<%=o.hash_id%>">
              <td>
                <%=o.hash_id%>
                <% if o.conekta_order_id.present? %>
                  <p>Conekta id: <b><%= o.conekta_order_id %></b></p>
                <% elsif o.bbva_charge_id.present? %>
                  <p>Bbva id: <b><%= o.bbva_charge_id %></b></p>
                <% end %>  
              </td>
              <td><%= o.Client.email %></td>
              <% o_city = o.City %>
              <td><%= o_city.name %>, <%= o_city.State.name %></td>
              <td><%= link_to o.Client.name, admin_client_path(o.Client) %></td>
              <td><%= o.Client.telephone %></td>
              <td>
                <% if o.distributor_id != 0 %>
                  <%= link_to o.Distributor.username, admin_distributor_path(o.Distributor.hash_id) %>
                <% elsif o.Client.worker_id.present? %>
                  <% worker = o.Client.Worker %>
                  <%= link_to worker.name, admin_site_workers_path(worker) %>
                <% else %>
                  <b> Sin distribuidor en la zona </b>
                <% end # if o.distributor_id != 0 # %>
              </td>
              <td>
                <span class="<%=@label_styles[o.state]%>">
                  <%=t(o.state)%>
                </span>
              </td>
              <td>$ <%= o.total %></td>
              <td>
                <%# render partial: "hidden_row", locals: {o: o} %>
              </td>
              <td class="text-center">
                <% if o.payment.present? %>
                  <%= link_to admin_download_payment_path(o.download_payment_key), target: "_blank" do %>
                    <i class="fa fa-file-o fa-3x"></i>
                  <% end %><br>
                <% end # if o.payment.present? # %>
              </td>
              <td><%= l(o.created_at, format: :long) %></td>
              <td>
                <%= link_to admin_order_details_path(o.hash_id), target: "_blank",
                  class: "btn btn-white btn-sm m-b-xs hidden-button" do %>
                  <i class="fa fa-eye"></i> Ver pedido
                <% end %>

                <% if @current_user.has_permission?('orders@capture_batches') and o.state == "LOCAL" %>
                  <%= link_to "Capturar números de lote", admin_capture_details_path(o.hash_id),
                    class: "btn btn-white btn-sm m-b-xs hidden-button" %>
                <% end %>

                <% unless ["PAYMENT_ACCEPTED_LOCAL","LOCAL"].include? o.state %>
                  <%= form_for(o, url: admin_order_upload_payment_path(o.hash_id), method: :put,
                      data: {confirm: "Seguro(a) de ser el archivo correcto?"},
                      html: {style: 'display: contents;'}) do |f| %>

                    <%= f.file_field :payment, id: "field_#{o.hash_id}",
                      style: "display: none;", multiple: false,
                      onchange: "$('#payment_commit_#{o.hash_id}').click();" %>

                    <a href="#" onclick="$('#field_<%=o.hash_id%>').click();"
                      class="btn btn-white btn-sm m-b-xs hidden-button">
                      Subir comprobante
                    </a>

                    <%= f.submit "Subir foto del pago".html_safe,
                      id: "payment_commit_#{o.hash_id}", style: "display: none;" %>
                  <% end %>
                <% end %>

                <% if @current_user.has_permission?('orders@cancel') and o.state == 'LOCAL' %>
                  <a class="btn btn-danger btn-sm m-b-xs hidden-button"
                    onclick="update_cancel_form('<%=o.hash_id%>')">
                    <i class="fa fa-trash"></i> Cancelar
                  </a>
                <% end %>

                <% if @current_user.has_permission?("commissions@create") and 
                  o.state == "PAYMENT_ACCEPTED_LOCAL" and params[:distributor].present? and
                  !o.commission_in_progress%>&nbsp;&nbsp;&nbsp;
                  <%= check_box_tag "order", o.hash_id, false, autocomplete: :off,
                    onchange: "update_orders_for_commission(this)" %>
                <% end %>

              </td>
              <td>
                <% if @current_user.has_permission?('orders@accept_reject_payment') and 
                  o.state == "PICKED_UP" and o.payment.present? %>
                  <%= form_tag admin_accept_order_pay_path(o.hash_id, "true"), method: :put do  %>
                    <%= hidden_field_tag :local_order, true %>
                    <%= label_tag :payment_folio, 'Folio del pago/depósito' %>
                    <%= text_field_tag :payment_folio, '', class: 'form-control', required: true %>
                    <%= submit_tag 'Aceptar', class: 'btn btn-primary btn-sm m-t',
                      data:{confirm: 'Seguro(a) de aceptar el pago?'} %>
                  <% end %>
                <% end # if o.state == "PAYMENT_DEPOSITED" # %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="7">
              <div class="pull-right">
                <% if @orders %>
                  <%= will_paginate @orders, renderer: BootstrapPagination::Rails %>
                <% end %>
              </div>
            </td>
          </tr>
        </tfoot>
      </table>

      <script>
        $(document).ready(function() {
            $('.footable').footable();
        });

        function update_cancel_form(target){
          $("#cancel_modal").modal("show");

          new_action = "<%= admin_cancel_order_path(0) %>";
          new_action = new_action.replace("0", target);

          $("#cancel_form").attr("action", new_action);
        }
        
        function update_orders_for_commission(checkbox){
          let commission_form = $("#create-commission-form");

          if(checkbox.checked){
            input = `<input type="hidden" name="order_keys[]" 
              value="${checkbox.value}" 
              id="order-key-${checkbox.value}"></input>`;
            commission_form.append(input);
          }else{
            $(`#order-key-${checkbox.value}`).remove();
          }
        }
      </script>

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal inmodal in" id="cancel_modal" tabindex="-1"
     role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Cancelar orden/pedido</h4>
      </div>
      <div class="modal-body">
        <%= form_for :order, url: admin_cancel_order_path(0), method: :delete, html: {id: "cancel_form"} do |f| %>
          <%= f.label :cancel_description, "Descripción del por qué se cancela esta orden/pedido" %>
          <%= f.text_area :cancel_description, class: "form-control m-b", placeholder: "Escribe la razón de la cancelación...", required: true %>
          <%= f.submit "Cancelar la orden", class: "btn btn-danger btn-sm", data:{confirm: "¿Seguro(a) de cancelar la orden?"} %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-greenbeauty" data-dismiss="modal"> Cerrar </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/admin/orders/show_activities.html.erb
<% provide(:title, "Acciones") %>
<%= render partial: "/shared/admin/header_band", locals: {title: "Acciones", labels: ["Cierre de día", "Acciones"], links: [admin_orders_search_path(initial_hour: params[:initial_hour], end_hour: params[:end_hour])]} %>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="ibox ibox-content">
      <h1>Acciones de la orden (historial)</h1>
      <table class="footable table table-stripped toggle-arrow-tiny">
        <thead>
          <th>Trabajador</th>
          <th>Acción</th>
          <th>-</th>
          <th>Fecha</th>
        </thead>
        <tbody>
          <% @actions.each do |action| %>
            <tr>
              <% worker = action.Worker %>
              <td><%= link_to worker.username, admin_site_worker_path(worker.hash_id), target: "_blank" %></td>
              <td colspan="2"><%=action.description%></td>
              <td><%= l(action.created_at, format: :long) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>