config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get '/good_bye/:id' => 'static_pages#good_bye', as: :good_bye
  post '/' => 'static_pages#create_suggestion'

  get '/get_cities' => 'static_pages#get_cities', as: :get_cities
  get '/privacy_policy' => 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_service' => 'static_pages#terms_of_service', as: :terms_of_service

  get '/distributor_request' => 'static_pages#new_distributor_request', as: :distributor_request
  post '/distributor_request' => 'static_pages#create_distributor_request'
  get '/callbacks/bbva/:id' => 'static_pages#bbva_callback', as: :bbva_callback

  get 'log_in/' => 'sessions#new'
  post   'log_in/'   => 'sessions#create'
  delete 'log_out/'  => 'sessions#destroy'
  get 'forgot_password' => 'sessions#forgot_password', as: :forgot_password
  post 'forgot_password' => 'sessions#forgot_password'
  get 'recover_password/:token' => 'sessions#recover_password', as: :recover_password
  post 'recover_password/:token' => 'sessions#recover_password'
  post 'update_password' => 'sessions#update_password', as: :update_password

  get '/products' => 'products#index', as: :products
  get '/products/:id' => 'products#show', as: :product
  post '/products/:id/ask' => 'products#ask', as: :product_ask

  get '/tips&recipes' => "tips#index", as: :tips
  post '/tips&recipes/:id/new_comment' => "tips#create_comment", as: :create_tip_comment
  get '/tips&recipes/:id' => "tips#show", as: :tip

  namespace :admin do
    get '/' => 'welcome#index', as: :welcome
    get '/suggestions' => 'welcome#suggestions', as: :suggestions
    post '/suggestion/:id/send_answer' => 'welcome#answer_suggestion', as: :answer_suggestion
    get '/notifications' => 'welcome#notifications', as: :notifications
    post '/update_ui_theme/:theme' => 'welcome#update_ui_theme', as: :update_ui_theme

    get '/clients' => 'clients#index', as: :clients
    get '/clients/:id' => 'clients#show', as: :client
    get '/clients/:id/orders' => 'clients#orders', as: :client_orders
    get '/clients/:id/prices' => 'clients#prices', as: :client_prices
    get '/clients/:id/revisions' => 'clients#revisions', as: :client_revisions
    get '/clients/:id/visits' => 'clients#visits', as: :client_visits

    get 'mexico-db/states' => 'mexico_db#index', as: :mexico_db
    get 'mexico-db/states/:id' => 'mexico_db#state', as: :mexico_state
    put 'mexico-db/states/:id' => 'mexico_db#update_state_lada'
    put 'mexico-db/states/cities/:id' => 'mexico_db#update_city', as: :mexico_city
    post 'mexico-db/states/cities' => 'mexico_db#create_city', as: :create_city

    resources :banks, except: :show do
      resources :bank_accounts, except: :show, as: 'accounts'
    end

    resources :site_workers do
      get 'permissions/edit', action: :edit_permissions, on: :member, as: :edit_permissions
      put 'permissions', action: :update_permissions, on: :member, as: :update_permissions
    end

    resources :distributors
    resources :distributor_regions, path: 'distributor/:dist_id/regions', except: [ :edit, :update, :show, :new ]
    get '/distributors/candidates/list' => 'distributors#candidates', as: :distributor_candidates
    post '/distributors/candidate/:id/answer' => 'distributors#answer_candidate', as: :answer_candidate

    get 'distributor_work/clients/' => 'distributor_work#index', as: :distributor_work_clients
    put 'distributor_work/clients/:id/take' => 'distributor_work#take_client', as: :distributor_work_take_client
    get 'distributor_work/my_clients/' => 'distributor_work#my_clients', as: :distributor_work_my_clients
    get 'distributor_work/client/:id/prices' => 'distributor_work#prices', as: :distributor_work_client_prices
    post 'distributor_work/client/:id/prices' => 'distributor_work#create_prices', as: :distributor_work_client_create_prices
    get 'distributor_work/my_clients/orders' => 'distributor_work#orders', as: :distributor_work_orders

    get 'distributor_work/client/:id/messages' => 'distributor_work#messages', as: :distributor_work_client_messages
    post 'distributor_work/client/:id/messages' => 'distributor_work#create_message'
    post 'distributor_work/client/:id/transfer' => 'distributor_work#transfer_client', as: :distributor_work_transfer_client

    resources :products
    get '/products/:id/photo/:photo_id/update' => "products#set_principal_photo", as: :products_set_principal
    get '/products/:id/photo/:photo_id/destroy' => "products#destroy_photo", as: :products_photo_destroy
    resources :product_questions, only: [ :index, :create ]
    get 'product_questions/answered' => 'product_questions#answered', as: :product_answered_questions

    resources :warehouses
    resources :warehouse_regions, path: 'warehouses/:warehouse_id/regions', except: [ :edit, :update, :show, :new ]

    resources :warehouse_products, path: 'warehouses/:warehouse_id/products', only: [ :index ]

    get 'warehouses/batch/search' => 'warehouses#batch_search', as: :batch_search
    get 'warehouses/:warehouse_id/inventory/impression_format' => 'warehouses#inventory', as: :inventory

    get 'warehouses/:warehouse_id/products/:id/stock_details' => 'warehouse_products#stock_details', as: :warehouse_products_stock_details
    put 'warehouses/:warehouse_id/products/:id/stock_details' => 'warehouse_products#update_stock'

    get 'chief/warehouses/:warehouse_id/products' => 'warehouse_products#chief_index', as: :chief_warehouse_products
    post 'chief/warehouses/:warehouse_id/products/:id/prepare_for_shipment' => 'warehouse_products#prepare_product_for_shipment', as: :prepare_product_for_shipment
    delete 'chief/warehouses/:warehouse_id/products/preparations/:id' => 'warehouse_products#discard_shipment_preparation', as: :discard_shipment_preparation
    put 'chief/warehouses/:warehouse_id/products/:id/update_min_stock' => 'warehouse_products#update_min_stock', as: :update_product_min_stock

    get 'chief/warehouses/:warehouse_id/shipments' => 'warehouse_products#chief_shipments', as: :chief_shipments
    post 'chief/warehouses/:warehouse_id/shipments' => 'warehouse_products#create_shipment'
    get 'chief/warehouses/:warehouse_id/shipment/:id/details' => 'warehouse_products#chief_shipment_details', as: :chief_shipment_details
    delete 'chief/warehouses/:warehouse_id/shipment/:id' => 'warehouse_products#destroy_shipment', as: :chief_destroy_shipment

    post 'chief/warehouses/print_qr' => 'warehouse_products#print_qr', as: :print_qr

    get 'warehouses/:warehouse_id/shipments' => 'warehouse_products#shipments', as: :shipments
    get 'warehouses/:warehouse_id/shipment/:id/details' => 'warehouse_products#shipment_details', as: :shipment_details
    post 'warehouses/:warehouse_id/shipment/:id/received_it_complete' => 'warehouse_products#receive_complete_shipment', as: :receive_complete_shipment

    post 'warehouses/:warehouse_id/shipment/:id/add_report_quantity_to_stock' => 'warehouse_products#add_report_quantity_to_stock', as: :add_report_quantity_to_stock
    post 'warehouses/:warehouse_id/shipment/:id/difference_report' => 'warehouse_products#create_difference_report', as: :difference_report

    get 'orders/' => 'orders#index', as: :orders
    put 'order/:id/accept_pay/:accept' => 'orders#accept_pay', as: :accept_order_pay

    get 'order/:id/details' => 'orders#details', as: :order_details

    delete 'order/:id' => 'orders#cancel', as: :cancel_order
    put 'order/:id/inspection' => 'orders#inspection', as: :inspection_order
    put 'order/:id/supply_error' => 'orders#supply_error', as: :order_supply_error
    get 'order/:id/capture_details' => 'orders#capture_details', as: :capture_details
    post 'order/:id/capture_details' => 'orders#save_details'
    put 'order/:id/capture_tracking_code' => 'orders#save_tracking_code', as: :capture_tracking_code
    put 'order/:id/delivered' => 'orders#save_as_delivered', as: :order_delivered
    put 'order/:id/invoice' => 'orders#invoice_delivered', as: :order_invoice_delivered
    get 'order/:payment_key/download_payment_file' => 'orders#download_payment_file', as: :download_payment
    put 'order/:id/upload_payment' => 'orders#upload_payment', as: :order_upload_payment

    get 'orders/search' => 'orders#search', as: :orders_search
    get 'order/:id/show_activities' => 'orders#show_activities', as: :show_order_activities

    get 'orders/invoice/download' => 'orders#download_invoice_data', as: :download_orders_invoice_data

    put 'orders/:id/invoice_folio' => 'orders#save_invoice_folio', as: :order_save_invoice_folio

    get 'bank_report/' => 'bank_reports#index', as: :bank_report
    post 'bank_report/' => 'bank_reports#show'

    get "clients/:id/supervisor_visits/" => 'clients#supervisor_visits', as: :supervisor_visits
    get "clients/:id/supervisor_visits/:visit_id/details" => 'clients#supervisor_visit_details', as: :supervisor_visit_details
    get "clients/:id/supervisor_visits/new" => 'clients#new_supervisor_visit', as: :new_supervisor_visit
    post "clients/:id/supervisor_visits/new" => 'clients#create_supervisor_visit'

    get 'statistics' => 'statistics#index', as: :statistics
    post 'statistics/sales' => 'statistics#sales', as: :sales_statistics
    post 'statistics/best_distributors' => 'statistics#best_distributors', as: :best_dist_statistics
    post 'statistics/best_clients' => 'statistics#best_clients', as: :best_clients_statistics

    get 'web' => 'web#index', as: :web
    get 'web/video' => 'web#videos', as: :web_videos
    post 'web/video' => 'web#upload_video'
    delete 'web/video' => 'web#reset_videos'

    get 'web/gallery' => 'web#photos', as: :web_photos
    post 'web/gallery' => 'web#upload_photos'
    delete 'web/gallery/:id' => 'web#destroy_photo', as: :web_destroy_photo

    get 'web/offers' => 'web#offers', as: :web_offers
    post 'web/offers' => 'web#upload_offers'
    delete 'web/offers/:id' => 'web#destroy_offer', as: :web_destroy_offer

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < AdminController

  def index
    deny_access! and return unless @current_user.has_permission_category?("clients")

    if params[:distributor]
      distributor = Distributor.find_by!(hash_id: params[:distributor])
      region_ids = distributor.Regions.map(&:id)

      if region_ids.empty?
        flash[:info] = "El distribuidor \"#{distributor.username}\" no tiene zonas asignadas."
        redirect_to admin_distributors_path and return
      end
    end

    @clients = Client.active.recent.byRegion(region_ids)
      .search(key_words: search_params, joins: {City: :State}, fields: fields_to_search)
      .paginate(page: params[:page], per_page: 20).includes(City: :State)
  end

  def show
    deny_access! and return unless @current_user.has_permission_category?("clients")

    @client = Client.find_by!(hash_id: params[:id])
    @fiscal_data = @client.FiscalData
  end

  def orders
    deny_access! and return unless @current_user.has_permission_category?("clients")

    @client = Client.find_by!(hash_id: params[:id])

    @client_city = @client.City
    @orders = @client.Orders.order(updated_at: :desc).paginate(page: params[:page], per_page: 15)
  end

  def revisions
    deny_access! and return unless @current_user.has_permission_category?("clients")

    @client = Client.find_by!(hash_id: params[:id])

    @client_city = @client.City
    @revisions = @client.DistributorRevisions.order(created_at: :desc)
      .paginate(page: params[:page], per_page: 15)
  end

  def visits
    deny_access! and return unless @current_user.has_permission_category?("clients")

    @client = Client.find_by!(hash_id: params[:id])

    @client_city = @client.City
    @visits = @client.DistributorVisits.where("client_recognizes_visit is not null")
      .order(created_at: :desc).paginate(page: params[:page], per_page: 15)
  end

  def prices
    deny_access! and return unless @current_user.has_permission_category?("clients")

    @client = Client.find_by!(hash_id: params[:id])

    @client_city = @client.City
    @products = Product.active.order(name: :asc).paginate(page: params[:page], per_page: 15)
    @prices = @client.ProductPrices
  end

  def supervisor_visits
    deny_access! and return unless @current_user.has_permission?("clients@supervisor_visit")

    @client = Client.find_by!(hash_id: params[:id])

    @client_city = @client.City

    @visits = @client.SupervisorVisits.order(created_at: :desc)
      .paginate(page: params[:page], per_page: 25).includes(:Supervisor)
  end

  def supervisor_visit_details
    deny_access! and return unless @current_user.has_permission?("clients@supervisor_visit")

    @detail = SupervisorVisitDetail.find_by!(visit_id: params[:visit_id])
  end

  def new_supervisor_visit
    deny_access! and return unless @current_user.has_permission?("clients@supervisor_visit")

    @visit_detail = SupervisorVisitDetail.new
  end

  def create_supervisor_visit
    deny_access! and return unless @current_user.has_permission?("clients@supervisor_visit")

    client = Client.find_by!(hash_id: params[:id])

    visit = SupervisorVisit.new(worker_id: @current_user.id, client_id: client.id)
    @visit_detail = SupervisorVisitDetail.new(visit_params)

    ActiveRecord::Base.transaction do
      visit.save!
      @visit_detail.visit_id = visit.id
      @visit_detail.save!
      flash[:success] = "Se guardaron los datos de la encuesta."
    end

    unless flash[:success].present?
      flash[:info] = "Ocurrió un error al guardar la encuesta"
      render :new_supervisor_visit and return
    end
    redirect_to admin_clients_path
  end

  private
    def fields_to_search
      return ["cities.name","states.name","clients.name",
        "clients.email", "clients.hash_id"]
    end

    def visit_params
      params.require(:supervisor_visit_detail).permit(:client_type, :location, :local_size,
        :instalations, :infrastructure, :visibility, :motor_traffic, :walker_traffic,
        :global_profile, :years_commerce, :consumers, :client_clients_opinion_our_product,
        :client_clients_opinion_his_products, :client_clients_opinion_his_service,
        :client_workers, :client_branches, :global_commerce, :product_quality, :product_assortment,
        :product_price, :product_taste, :product_packing, :packing_aspect, :product_expiration,
        :product_shipping_packing, :need_new_products, :visits, :worker_uniform, :distributor,
        :worker, :shipment, :shipment_time, :global_service, :web_easy, :purchase_system,
        :payment_system, :purchase_follow_up, :global_web, :extra_comments,
      )
    end
end

app/controllers/api/distributor_api/clients_controller.rb
class Api::DistributorApi::ClientsController < ApiController
  before_action do
    authenticate_user!(Distributor)
  end

  def index
    region_ids = @current_user.Regions.map(&:id)
    clients = Client.where(city_id: region_ids).order(updated_at: :DESC)
      .paginate(page: params[:page], per_page: 20).includes(City: :State)

    data = Array.new
    data << {per_page: 20}
    clients.each do |client|
      data << {
        hash_id: client.hash_id, name: client.name, city: client.City.name, is_new: client.is_new,
        state: client.City.State.name, last_visit: client.last_distributor_visit, 
        last_revision: client.last_distributor_revision, photo: client.avatar_url,
        telephone: client.telephone, cellphone: client.cellphone, lada: client.City.lada
      }
    end

    render status: 200, json: {success: true, info: "DATA_RETURNED", data: data}
  end

  def show
    client = Client.find_by!(hash_id: params[:id])

    data = {
      name: client.name, email: client.email, street: client.street,
      colony: client.col, intnumber: client.intnumber, 
      extnumber: client.extnumber, zipcode: client.cp, 
      street_ref1: client.street_ref1, street_ref2: client.street_ref2,
      telephone: client.telephone, cellphone: client.cellphone, 
      city: client.City.name, state: client.City.State.name, 
      created_at: client.created_at, updated_at: client.updated_at
    }

    render status: 200, json: {success: true, info: "USER_DATA", data: data}
  end
end

app/controllers/api/workers_api/clients_controller.rb
class Api::WorkersApi::ClientsController < ApiController
  before_action do
    authenticate_user!(SiteWorker)
  end

  def show
    order = Order.find_by!(hash_id: params[:id])
    c = order.Client

    data = {username: c.username, email: c.email, street: c.street,
            colony: c.col, intnumber: c.intnumber, extnumber: c.extnumber,
            zipcode: c.cp, street_ref1: c.street_ref1, street_ref2: c.street_ref2,
            telephone: c.telephone, birthday: c.birthday, cellphone: c.cellphone,
            name: c.name, lastname: c.lastname, mother_lastname: c.mother_lastname,
            photo: c.avatar_url}

    render status: 200, json: {success: true, info: "DATA_RETURNED",
      data: data, city_name: c.City.name, state_name: c.City.State.name}
  end

end

app/controllers/distributor/admin_controller.rb
class Distributor::AdminController < ApplicationController
  before_action -> { user_should_be(Distributor) }
  layout "distributor_layout.html.erb"

  def index
    @regions = @current_user.Regions
  end

  def prices
    @products = Product.active.order(name: :asc)
      .paginate(page: params[:page], per_page: 25)
  end

  def update_home_image
    @current_user.update_attribute(:home_img, params[:distributor][:home_img])
    flash[:success] = "Imagen guardada"
    redirect_to distributor_welcome_path
  end

  def notifications
    @notifications = @current_user.Notifications.order(created_at: :desc)
      .limit(50).paginate(page: params[:page], per_page: 15)
  end

  def update_ui_theme
    @current_user.update_attribute(:ui_theme, params[:theme])
    render status: 200, json: {success: true, new_theme: params[:theme] }
  end

end

app/views/distributor/clients/_presentation_table.html.erb
<div class="col-lg-12">
  <div class="ibox">
  	<div class="ibox-content">

  			<div class="row m-b-sm m-t-sm">
          <div class="col-md-10">
            <input type="text" class="form-control input-sm m-b-xs" id="filter" placeholder="Buscar en tabla">
          </div>
  				<div class="col-md-2">
  					<%= link_to(distributor_clients_path, class: "btn btn-white btn-sm full-width") do %>
  						<i class="fa fa-refresh"></i> Actualizar
  					<% end %>
  				</div>
  			</div>

  			<table class="footable table table-stripped  toggle-arrow-tiny" data-filter=#filter>
  					<thead>
    					<tr>
                  <th data-sort-ignore="true"></th>
    					    <th data-hide="phone" data-sort-ignore="true"></th>
    					    <th data-hide="phone">Nombre</th>
    					    <th>Correo electrónico</th>
    					    <th data-hide="phone">Ubicación</th>
    					    <th data-hide="all">Teléfono</th>
                  <th data-hide="phone">Acciones</th>
                  <th data-hide="all">Última revisión</th>
                  <th data-hide="all">Última visita</th>
    					</tr>
  					</thead>
  					<tbody>
  					<% @clients.each do |c| %>
  					  <tr>
                <td></td>
    						<td class="project-people">
                  <%= link_to distributor_client_path(c.hash_id) do %>
                    <% if !c.photo.blank? %>
                        <%= image_tag(c.photo.url(:mini), { class: "img-circle" }) %>
                    <% else %>
                        <%= image_tag("user_avatar.png", { class: "img-circle" }) %>
                    <% end %>
                  <% end %>
    						</td>
    						<td>
                  <%= c.name %>
                  <% if c.is_new %><br>
                    <label class="label label-primary"> Nuevo </label>
                  <% end %>
                </td>
    						<td><%= c.email %></td>
    						<td><%= c.City.name %>, <%= c.City.State.name %></td>
    						<td>(<%=c.City.lada%>) <%= c.telephone %></td>
                <td>
                  <%= link_to distributor_client_prices_path(c.hash_id),
                    class: "btn btn-white btn-sm m-b-xs hidden-button" do %>
                    <i class="fa fa-pencil"></i> Precios
                  <% end %>

                  <%= link_to distributor_orders_path(client: c.hash_id),
                    class: "btn btn-white btn-sm m-b-xs hidden-button" do %>
                    <i class="fa fa-truck"></i> Órdenes
                  <% end %>

                  <%= link_to distributor_client_visits_path(c.hash_id),
                    class: "btn btn-white btn-sm m-b-xs hidden-button" do %>
                    <i class="fa fa-calendar"></i> Visitas
                  <% end %>

                  <%= link_to distributor_client_messages_path(c.hash_id),
                    class: "btn btn-white btn-sm m-b-xs hidden-button" do %>
                    <i class="fa fa-envelope-o"></i> Mensajes
                  <% end %>
                </td>
                <td><%= c.last_distributor_revision %></td>
                <td><%= c.last_distributor_visit %></td>
  					  </tr>
  					<% end %>
  					</tbody>
            <tfoot>
              <tr>
                <td colspan="7">
                  <div class="pull-right">
                    <%= will_paginate @clients, renderer: BootstrapPagination::Rails %>
                  </div>
                </td>
              </tr>
            </tfoot>
  			</table>

        <script>
            $(document).ready(function() {
                $(".footable").footable();
            });
        </script>

  	</div>
  </div>
</div>

app/views/distributor/clients/create_message.js.erb
<% to_render = j render partial: "/shared/message", locals: {message: @message} %>
$("#messages-container").prepend("<%= to_render %>");
$("#comment").val("");
removeLoader();

app/views/distributor/clients/index.html.erb
<% provide(:title, "Clientes") %>
<%= render partial: "/shared/distributor/header_band", 
  locals: {title: "Clientes", labels: ["Clientes"]} %>

<!--Content whit animation-->
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">

    <div class="ibox">
      <div class="ibox-content text-center">
        <h3 class="m-b-xxs">Lista de clientes</h3>
      </div>
    </div>

    <div class="row">
      <%= render partial: "presentation_table" %>
    </div>

  </div>
</div>
<!--End content whit animation-->
<br><br>

app/views/distributor/clients/messages.html.erb
<% provide(:title, "Mensajes") %>
<%= render partial: "/shared/distributor/header_band", locals: {title: "Mensajes", 
  labels: ["Clientes", "Mensajes"], links: [distributor_clients_path]} %>
<br>
<%= render "shared/client_head_bar" %>

<%= render partial: "shared/messages", locals: {messages: @messages, create_message_url: @create_message_url} %>

app/views/distributor/clients/prices.html.erb
<% provide(:title, "Precios") %>
<%= render partial: "/shared/distributor/header_band", locals: {title: "Precios del cliente", 
  labels: ["Clientes", "Precios"], links: [distributor_clients_path]} %>

<div class="wrapper wrapper-content">
  <div class="row animated fadeInRight">
    <div class="row">

      <div class="col-lg-12">
        <%= render "/shared/client_head_bar" %>
      </div>

      <div class="col-lg-12">
        <div class="ibox ibox-content">
          <h3>Listado de precios</h3>

          <% if @client.has_custom_prices %>
            <div class="alert alert-success">
              <i class="fa fa-check"></i> El cliente ya cuenta con precios definidos
            </div>
          <% else %>
            <div class="alert alert-warning">
              <i class="fa fa-warning"></i> El cliente aún no cuenta con precios definidos
            </div>
          <% end %>

        </div>
      </div>

      <div class="col-lg-12">
        <!--Table-->
        <div class="ibox">
            <div class="ibox-content">

                <div class="row m-b-sm m-t-sm">
                  <div class="col-md-8">
                    <input type="text" class="form-control input-sm m-b-xs" id="filter" placeholder="Buscar en tabla">
                  </div>
                  <div class="col-md-4">
                    <span>Establecer precios: </span><br>
                    <i class="btn btn-white btn-sm"
                        onclick="update_product_prices('min')">
                        Mínimos
                    </i>
                    <i class="btn btn-white btn-sm"
                        onclick="update_product_prices('recommended')">
                        Recomendados
                    </i>
                    <i class="btn btn-white btn-sm"
                        onclick="update_product_prices('max')">
                        Máximos
                    </i>
                  </div>
                </div>
                <%= form_tag(distributor_client_create_prices_path(@client.hash_id)) do %>
                  <!--<div class="table-responsive">-->
                  <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15" data-filter=#filter>
                      <thead>
                      <tr>
                          <th>Producto</th>
                          <th data-sort-ignore="true"></th>
                          <th data-hide="all">Precio mínimo</th>
                          <th data-hide="all">Precio recomendado</th>
                          <th data-hide="all">Precio máximo</th>
                      </tr>
                      </thead>
                      <tbody>
                        <% @products.each do |p| %>
                          <tr>
                            <td><%= label_tag "product[#{p.id}]", p.name %></td>
                            <% field_value = nil
                               if @product_prices.any?
                                 @product_prices.each do |pp|
                                   if pp.product_id == p.id
                                     field_value = pp.client_price
                                     break
                                   end
                                 end # @product_prices.each #
                               end # if @product_prices.any? # %>
                            <td>
                              <%= number_field_tag "product[#{p.id}]", field_value,
                                  {class: "form-control product-control", max: p.price,
                                   recommended: p.recommended_price, min: p.lowest_price,
                                   step: 0.01, required: "required"} %>
                                   <span class="help-block m-b-none">Escribe el precio pactado para "<%= p.name %>".</span>
                            </td>
                            <td>$ <%= p.lowest_price %></td>
                            <td>$ <%= p.recommended_price %></td>
                            <td>$ <%= p.price %></td>
                          </tr>
                        <% end %>
                      </tbody>
                      <tfoot>
                        <tr>
                          <td colspan="2">
                            <br>
                            <div class="pull-right">
                              <i class="btn btn-white"
                                 onclick="update_product_prices_to_default()">
                                 Establecer todos los precios recomendados
                              </i>
                              <%= submit_tag :Guardar, class: "btn btn-primary" %>
                            </div>
                          </td>
                        </tr>
                      </tfoot>
                  </table>
                <% end %>
            </div>
        </div>
      </div>
      <br>
      <!--End Table-->


    </div>
  </div>
</div>

<script type="text/javascript">
  function update_product_prices(price_type){
    products = $(".product-control");
    for(indx=0; indx<products.length; indx++){
      p = $(products[indx]);
      new_price = p.attr(price_type);
      p.val(new_price);
    }
  }
</script>

<script>
    $(document).ready(function() {
        $(".footable").footable();
    });
</script>